sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LzHfSPLKHH7b+4YJbVOv9TwiZfQs6uvoEvv+iMkrXY9SfVa+s2KYH4X7ubjzXv5QWntlpMeS6bSJIcXSh+3ZdAq8G2jN8h/m1rT5mrNbXmagLkmW++aX5FMb/ybL9HJronmR8W3ZyR5R0ViHEIoLc+Y9cv0mRu9QdT6rT5oXBy4VIXfxbOdMbxUKvwUgJBfSO/r11f5GUpVVIPwOQvKtm4Wte38Tf7ecE7HBpN1I+WJZk7hlbUtC6Fko7V/dsP+4MKOuGJjpEEpZBhTKJ7jrE9+H1uhYIITo34/4WFrKn8Bi6aemHeRNWvouksTAtV/wtli9CcSWQ4tHDV5gLmWhnthjJz8mz/VqHshZKMfQT+f5oJtukeqtsYAcncIwxbChvleocAhu67X6szjpN7StGaMyHierLPPawriYFZD3Wcu6VNtZQYFnhf46msrea64xvVlX+ALqKKSBFtHvf+dkE4Nz152HlRmE8RjHtq8zNPwBSsGq98rrbIMuSsaKY/jAv8GclBpXWP1v83hleQOWVpGgqVR9FDaZIgy3L9c6P6OgtjKtdlyfV/rSLX47O8n8P6BVRVvFPthlq4QRKG8HM1l2S6oTJDydo/GEDJSqepIQmitddPxm1dUyYclRBUKW21vHVVoVEaGslwBl05bs/7uDq/C/wjke5R9ILOone/Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Boy-Aviators-Treasure-Quest-Or-The-Golden-Galleon_6149
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy